plots:
  title: "CPF_test"
  xlabel: "Northing [m]"
  ylabel: "Easting [m]"
  # mod: "slap"
  image:
    samples: 10 # 30
    mirror: True
    # limits:         # comment out if you want to use automatic limits 
    #   xlim: [4290815, 4290855]
    #   ylim: [491940, 491960]
  curves:
    - file: "lawnmower_mvector.mat"   # file where to find the data
      topic: "usbl_meas"              # word to find on topic with data
      legend: "mvector_usbl"          # legend for the plot
      color: "purple"                 # color to plot with
    # - file: "lawnmower_mvector.mat"
    #   topic: "dead_reckoning"
    #   legend: "mvector_dr"
    #   color: "orange"
    - file: "lawnmower_mvector.mat"
      topic: "nav"
      legend: "mvector_nav"
      color: "yellow"
    - file: "lawnmower_mblack.mat"
      topic: "nav"
      legend: "mblack_nav"
      color: "black"
    - file: "lawnmower_mred.mat"
      topic: "nav"
      legend: "mred_nav"
      color: "red"
  # movie:
  #   duration: 30 # in seconds
  #   factor: 64 # determines the number of frames per second; the lower the factor, the more fps

# plots:
#   title: "SLAP_test"
#   xlabel: "Easting [m]"
#   ylabel: "Northing [m]"
#   mod: "slap"
#   image:
#     samples: 6
#     limits:         # comment out if you want to use automatic limits 
#       xlim: [491875, 492000]
#       ylim: [4290775, 4290870]
#   curves:
#     - file: "SLAP_mvector_target.mat"   # file where to find the data
#       topic: "usbl"                     # word to find on topic with data
#       legend: "mvector_usbl"            # legend for the plot
#       color: "purple"                   # color to plot with
#     - file: "SLAP_mvector_target.mat"
#       topic: "nav"
#       legend: "mvector_nav"
#       color: "yellow"
#     - file: "SLAP_mblack_tracker.mat"
#       topic: "nav"
#       legend: "mblack_nav"
#       color: "black"
#     - file: "SLAP_mblack_tracker.mat"
#       topic: "pdf"
#       legend: "mblack_target_pdf"
#       color: "black"
#     - file: "SLAP_mred_tracker.mat"
#       topic: "nav"
#       legend: "mred_nav"
#       color: "red"
#     - file: SLAP_mred_tracker.mat
#       topic: "pdf"
#       legend: "mred_target_pdf"
#       color: "red"
#   movie:
#     duration: 30 # in seconds
#     factor: 64 # determines the number of frames per second; the lower the factor, the more fps