# The yaml filename defines the folder where all plots will be saved.
# In x axis: if vehicles are not specified, this plot will be done
# for all vehicles independently.
# In x axis: if topics are not specified, default x axis value will
# be Time
plots:
  altitude:
    name: "Altitude"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: "Altitude [m]"
        topics:
          - "drivers/gps"
        fields:
          - "altitude"
    plot_markers:
      - "lines"
  course:
    name: "Course"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/gps"
        fields:
          - "course"
    plot_markers:
      - "lines"
  latitude:
    name: "Latitude"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: "Latitude [m]"
        topics:
          - "drivers/gps"
        fields:
          - "latitude"
    plot_markers:
      - "lines"
  longitude:
    name: "Longitude"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: "Longitude [m]"
        topics:
          - "drivers/gps"
        fields:
          - "longitude"
    plot_markers:
      - "lines"
  mode:
    name: "Mode"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/gps"
        fields:
          - "mode"
    plot_markers:
      - "lines"
  satellites:
    name: "Satellites"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/gps"
        fields:
          - "satellites"
    plot_markers:
      - "lines"
  speed_over_ground:
    name: "Speed over ground"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: "Speed [m/s]"
        topics:
          - "drivers/gps"
        fields:
          - "speed_over_ground"
    plot_markers:
      - "lines"
  utc_time:
    name: "UTC Time"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/gps"
        fields:
          - "utc_time"
    plot_markers:
      - "lines"