# List of drivers
driver_list:
  - "thruster"
  - "altimeter"
  - "batMonit"
  - "bluetooth" # TODO
  - "depthCell"
  - "gps"
  - "imu"
  - "insidePressure"
  - "leaks" # TODO
  - "parallel" # TODO
  - "navquest"
  - "batMonitRaw" # TODO

# Each new driver should specify:
#   topic: topic where the desired ros message is (after vehicle name)
#   plots: list of desired plots (OVER TIME)
#     name: plot name to be displayed
#     field: corresponding field in the ros message
#
# All drivers specified here should be at the above list!
drivers:
  thruster:
    topic: "drivers/Thruster" # + "0"/"1"/...
    plots:
      - name: "Current"
        field: "Current"
      - name: "Errors"
        field: "Erros"
      - name: "Speed"
        field: "Speed"
      - name: "Temperature"
        field: "Temperature"
  altimeter:
    topic: "drivers/altimeter/data"
    plots:
      - name: "Altimeter"
        field: "data"
  batMonit:
    topic: "drivers/bat_monit/data"
    plots:
      - name: "Actual charge"
        field: "actual_charge"
      - name: "Charging"
        field: "charging"
      - name: "Current"
        field: "current"
      - name: "Equalize"
        field: "equalize"
      - name: "Max cell"
        field: "max_cell"
      - name: "Max temp"
        field: "max_temp"
      - name: "Min cell"
        field: "min_cell"
      - name: "Min temp"
        field: "min_temp"
      - name: "Number of packs"
        field: "number_of_packs"
  # bluetooth:
  depthCell:
    topic: "drivers/depthCell"
    plots:
      - name: "Pressure"
        field: "pressure"
      - name: "Temperature"
        field: "temperature"
  gps:
    topic: "drivers/gps"
    plots:
      - name: "Altitude"
        field: "altitude"
      - name: "Course"
        field: "course"
      - name: "Latitude"
        field: "latitude"
      - name: "Longitude"
        field: "longitude"
      - name: "Mode"
        field: "mode"
      - name: "Satellites"
        field: "satellites"
      - name: "Speed over ground"
        field: "speed_over_ground"
      - name: "UTC Time"
        field: "utc_time"
  imu:
    topic: "drivers/imu"
    plots:
      ### imu ###
      - name: "Ax"
        field: "Ax"
      - name: "Ay"
        field: "Ay"
      - name: "Az"
        field: "Az"
      - name: "Gx"
        field: "Gx"
      - name: "Gy"
        field: "Gy"
      - name: "Gz"
        field: "Gz"
      - name: "Mx"
        field: "Mx"
      - name: "My"
        field: "My"
      - name: "Mz"
        field: "Mz"
      - name: "Pitch"
        field: "Pitch"
      - name: "Roll"
        field: "Roll"
      - name: "Yaw"
        field: "Yaw"
      ### imu_pp ### 
      - name: "Absolute Magnitude"
        field: "mag_abs"
      - name: "Mx"
        field: "mag_x"
      - name: "My"
        field: "mag_y"
      - name: "Mz"
        field: "mag_z"
  insidePressure:
    topic: "drivers/insidePressure"
    plots:
      - name: "Pressure"
        field: "pressure"
      - name: "Temperature"
        field: "temperature"
  # leaks:
  # parallel:
  navquest:
    topic: "drivers/navquest"
    plots:
      - name: "Depth Estimate"
        field: "depth_estimate"
      - name: "Error Code"
        field: "error_code"
      - name: "good_0"
        field: "good_0"
      - name: "good_1"
        field: "good_1"
      - name: "good_2"
        field: "good_2"
      - name: "good_3"
        field: "good_3"
      - name: "Pressure"
        field: "pressure"
      - name: "rph_0"
        field: "rph_0"
      - name: "rph_1"
        field: "rph_1"
      - name: "rph_2"
        field: "rph_2"
      - name: "Salinity"
        field: "salinity"
      - name: "Sound Speed"
        field: "sound_speed"
      - name: "Temperature"
        field: "temperature"
      - name: "v_depth_0"
        field: "v_depth_0"
      - name: "v_depth_1"
        field: "v_depth_1"
      - name: "v_depth_2"
        field: "v_depth_2"
      - name: "v_depth_3"
        field: "v_depth_3"
      - name: "velo_earth_0"
        field: "velo_earth_0"
      - name: "velo_earth_1"
        field: "velo_earth_1"
      - name: "velo_earth_2"
        field: "velo_earth_2"
      - name: "velo_earth_flag"
        field: "velo_earth_flag"
      - name: "velo_instrument_0"
        field: "velo_instrument_0"
      - name: "velo_instrument_1"
        field: "velo_instrument_1"
      - name: "velo_instrument_2"
        field: "velo_instrument_2"
      - name: "velo_instrument_flag"
        field: "velo_instrument_flag"
      - name: "velo_rad_0"
        field: "velo_rad_0"
      - name: "velo_rad_1"
        field: "velo_rad_1"
      - name: "velo_rad_2"
        field: "velo_rad_2"
      - name: "velo_rad_3"
        field: "velo_rad_3"
      - name: "water_velo_earth_0"
        field: "water_velo_earth_0"
      - name: "water_velo_earth_1"
        field: "water_velo_earth_1"
      - name: "water_velo_earth_2"
        field: "water_velo_earth_2"
      - name: "water_velo_earth_flag"
        field: "water_velo_earth_flag"
      - name: "water_velo_instrument_0"
        field: "water_velo_instrument_0"
      - name: "water_velo_instrument_1"
        field: "water_velo_instrument_1"
      - name: "water_velo_instrument_2"
        field: water_velo_instrument_2"
      - name: "water_velo_instrument_flag"
        field: "water_velo_instrument_flag"
      - name: "wvelo_credit_0"
        field: "wvelo_credit_0"
      - name: "wvelo_credit_1"
        field: "wvelo_credit_1"
      - name: "wvelo_credit_2"
        field: "wvelo_credit_2"
      - name: "wvelo_credit_3"
        field: "wvelo_credit_3"
      - name: "wvelo_rad_0"
        field: "wvelo_rad_0"
      - name: "wvelo_rad_1"
        field: "wvelo_rad_1"
      - name: "wvelo_rad_2"
        field: "wvelo_rad_2"
      - name: "wvelo_rad_3"
        field: "wvelo_rad_3"
  # batMonitRaw: