# The yaml filename defines the folder where all plots will be saved.
# In x axis: if vehicles are not specified, this plot will be done
# for all vehicles independently.
# In x axis: if topics are not specified, default x axis value will
# be Time
plots:
  wind_angle:
    name: "Wind Angle (Sensor Frame)"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: "Wind Angle (Sensor Frame) [deg]"
        topics:
          - "drivers/airmar_200wx/wind_angle"
        fields:
          - "data"
    plot_markers:
      - "lines"
  wind_speed:
    name: "Wind Speed (Sensor Frame)"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: "Wind Speed (Sensor Frame) [kn]"
        topics:
          - "drivers/airmar_200wx/wind_speed"
        fields:
          - "data"
    plot_markers:
      - "lines"