# The yaml filename defines the folder where all plots will be saved.
# In x axis: if vehicles are not specified, this plot will be done
# for all vehicles independently.
# In x axis: if topics are not specified, default x axis value will
# be Time
plots:
  Ax:
    name: "Accelerometer x"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/imu/data"
        fields:
          - "Ax"
    plot_markers:
      - "lines"
  Ay:
    name: "Accelerometer y"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/imu/data"
        fields:
          - "Ay"
    plot_markers:
      - "lines"
  Az:
    name: "Accelerometer z"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/imu/data"
        fields:
          - "Az"
    plot_markers:
      - "lines"
  Gx:
    name: "Gyroscope x"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/imu/data"
        fields:
          - "Gx"
    plot_markers:
      - "lines"
  Gy:
    name: "Gyroscope y"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/imu/data"
        fields:
          - "Gy"
    plot_markers:
      - "lines"
  Gz:
    name: "Gyroscope z"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/imu/data"
        fields:
          - "Gz"
    plot_markers:
      - "lines"
  Mx:
    name: "Magnetometer x"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/imu/data"
        fields:
          - "Mx"
    plot_markers:
      - "lines"
  My:
    name: "Magnetometer y"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/imu/data"
        fields:
          - "My"
    plot_markers:
      - "lines"
  Mz:
    name: "Magnetometer z"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/imu/data"
        fields:
          - "Mz"
    plot_markers:
      - "lines"
  Mx_vs_My:
    name: "Magnetometer x vs. Magnetometer y"
    axes:
      x:
        vehicles: # for all vehicles
        label: "Mx"
        topics:
          - "drivers/imu/data"
        fields:
          - "Mx"
      y:
        vehicles: # for all vehicles
        label: "My"
        topics:
          - "drivers/imu/data"
        fields:
          - "My"
    plot_markers:
      - "lines"
  pitch:
    name: "Pitch"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: "Degrees [ยบ]"
        topics:
          - "drivers/imu/data"
        fields:
          - "Pitch"
    plot_markers:
      - "lines"
  roll:
    name: "Roll"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: "Degrees [ยบ]"
        topics:
          - "drivers/imu/data"
        fields:
          - "Roll"
    plot_markers:
      - "lines"
  yaw:
    name: "Yaw"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: "Degrees [ยบ]"
        topics:
          - "drivers/imu/data"
        fields:
          - "Yaw"
    plot_markers:
      - "lines"
  mag_abs:
    name: "Absolute Magnitude"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/imu/imu_pp"
        fields:
          - "mag_abs"
    plot_markers:
      - "lines"
  mag_x:
    name: "Magnetometer x"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/imu/imu_pp"
        fields:
          - "mag_x"
    plot_markers:
      - "lines"
  mag_y:
    name: "Magnetometer y"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/imu/imu_pp"
        fields:
          - "mag_y"
    plot_markers:
      - "lines"
  mag_z:
    name: "Magnetometer z"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/imu/imu_pp"
        fields:
          - "mag_z"
    plot_markers:
      - "lines"