# The yaml filename defines the folder where all plots will be saved.
# In x axis: if vehicles are not specified, this plot will be done
# for all vehicles independently.
# In x axis: if topics are not specified, default x axis value will
# be Time
plots:
  pressure:
    name: "Pressure"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: "Pressure []"
        topics:
          - "drivers/inside_pressure_filter/data_dot"
        fields:
          - "data"
    plot_markers:
      - "lines"
  # temperature:
  #   name: "Temperature"
  #   axes:
  #     x: # time
  #     y:
  #       vehicles: # for all vehicles
  #       label: "Temperature [ºC]"
  #       topics:
  #         - "drivers/inside_pressure_filter/data_dot"
  #       fields:
  #         - "temperature"
  #   plot_markers:
  #     - "lines"
    