# The yaml filename defines the folder where all plots will be saved.
# In x axis: if vehicles are not specified, this plot will be done
# for all vehicles independently.
# In x axis: if topics are not specified, default x axis value will
# be Time
plots:
  depth_estimate:
    name: "Depth Estimate"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "depth_estimate"
    plot_markers:
      - "lines"
  error_code:
    name: "Error Code"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "error_code"
    plot_markers:
      - "lines"
  good_0:
    name: "good_0"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "good_0"
    plot_markers:
      - "lines"
  good_1:
    name: "good_1"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "good_1"
    plot_markers:
      - "lines"
  good_2:
    name: "good_2"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "good_2"
    plot_markers:
      - "lines"
  good_3:
    name: "good_3"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "good_3"
    plot_markers:
      - "lines"
  pressure:
    name: "Pressure"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "pressure"
    plot_markers:
      - "lines"
  rph_0:
    name: "rph_0"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "rph_0"
    plot_markers:
      - "lines"
  rph_1:
    name: "rph_1"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "rph_1"
    plot_markers:
      - "lines"
  rph_2:
    name: "rph_2"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "rph_2"
    plot_markers:
      - "lines"
  salinity:
    name: "Salinity"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "salinity"
    plot_markers:
      - "lines"
  sound_speed:
    name: "Sound Speed"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "sound_speed"
    plot_markers:
      - "lines"
  temperature:
    name: "Temperature"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "temperature"
    plot_markers:
      - "lines"
  v_depth_0:
    name: "v_depth_0"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "v_depth_0"
    plot_markers:
      - "lines"
  v_depth_1:
    name: "v_depth_1"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "v_depth_1"
    plot_markers:
      - "lines"
  v_depth_2:
    name: "v_depth_2"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "v_depth_2"
    plot_markers:
      - "lines"
  v_depth_3:
    name: "v_depth_3"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "v_depth_3"
    plot_markers:
      - "lines"
  velo_earth_0:
    name: "velo_earth_0"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "velo_earth_0"
    plot_markers:
      - "lines"
  velo_earth_1:
    name: "velo_earth_1"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "velo_earth_1"
    plot_markers:
      - "lines"
  velo_earth_2:
    name: "velo_earth_2"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "velo_earth_2"
    plot_markers:
      - "lines"
  velo_earth_flag:
    name: "velo_earth_flag"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "velo_earth_flag"
    plot_markers:
      - "lines"
  velo_instrument_0:
    name: "velo_instrument_0"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "velo_instrument_0"
    plot_markers:
      - "lines"
  velo_instrument_1:
    name: "velo_instrument_1"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "velo_instrument_1"
    plot_markers:
      - "lines"
  velo_instrument_2:
    name: "velo_instrument_2"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "velo_instrument_2"
    plot_markers:
      - "lines"
  velo_instrument_flag:
    name: "velo_instrument_flag"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "velo_instrument_flag"
    plot_markers:
      - "lines"
  velo_rad_0:
    name: "velo_rad_0"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "velo_rad_0"
    plot_markers:
      - "lines"
  velo_rad_1:
    name: "velo_rad_1"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "velo_rad_1"
    plot_markers:
      - "lines"
  velo_rad_2:
    name: "velo_rad_2"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "velo_rad_2"
    plot_markers:
      - "lines"
  velo_rad_3:
    name: "velo_rad_3"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "velo_rad_3"
    plot_markers:
      - "lines"
  water_velo_earth_0:
    name: "water_velo_earth_0"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "water_velo_earth_0"
    plot_markers:
      - "lines"
  water_velo_earth_1:
    name: "water_velo_earth_1"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "water_velo_earth_1"
    plot_markers:
      - "lines"
  water_velo_earth_2:
    name: "water_velo_earth_2"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "water_velo_earth_2"
    plot_markers:
      - "lines"
  water_velo_earth_flag:
    name: "water_velo_earth_flag"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "water_velo_earth_flag"
    plot_markers:
      - "lines"
  water_velo_instrument_0:
    name: "water_velo_instrument_0"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "water_velo_instrument_0"
    plot_markers:
      - "lines"
  water_velo_instrument_1:
    name: "water_velo_instrument_1"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "water_velo_instrument_1"
    plot_markers:
      - "lines"
  water_velo_instrument_2:
    name: "water_velo_instrument_2"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "water_velo_instrument_2"
    plot_markers:
      - "lines"
  water_velo_instrument_flag:
    name: "water_velo_instrument_flag"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "water_velo_instrument_flag"
    plot_markers:
      - "lines"
  wvelo_credit_0:
    name: "wvelo_credit_0"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "wvelo_credit_0"
    plot_markers:
      - "lines"
  wvelo_credit_1:
    name: "wvelo_credit_1"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "wvelo_credit_1"
    plot_markers:
      - "lines"
  wvelo_credit_2:
    name: "wvelo_credit_2"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "wvelo_credit_2"
    plot_markers:
      - "lines"
  wvelo_credit_3:
    name: "wvelo_credit_3"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "wvelo_credit_3"
    plot_markers:
      - "lines"
  wvelo_rad_0:
    name: "wvelo_rad_0"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "wvelo_rad_0"
    plot_markers:
      - "lines"
  wvelo_rad_1:
    name: "wvelo_rad_1"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "wvelo_rad_1"
    plot_markers:
      - "lines"
  wvelo_rad_2:
    name: "wvelo_rad_2"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "wvelo_rad_2"
    plot_markers:
      - "lines"
  wvelo_rad_3:
    name: "wvelo_rad_3"
    axes:
      x: # time
      y:
        vehicles: # for all vehicles
        label: ""
        topics:
          - "drivers/navquest"
        fields:
          - "wvelo_rad_3"
    plot_markers:
      - "lines"